### ISSUE TITLE
Implement "claim badge by claim code" API endpoint

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadger#121]
CSOL needs an endpoint to use to indicate that a logged in CSOL user is claiming a badge by claim code. This is related to #93.

**Comment by brianloveswords** [comment]
I believe @toolness is going to be working on the API parts while I'm gone, so this might be assigned to him.

**Comment by toolness** [comment]
Right on, I guess this is done. As cmcavoy mentioned [here](https://github.com/mozilla/openbadger/pull/136#discussion_r4403176) though, it looks like we should eventually add a GET endpoint that provides information about a badge given a claim code, so that the CSOL site and other clients can implement confirmation UIs.
