### ISSUE TITLE
Issue a badge to a single user, include evidence

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#122]
Allow a mentor to issue a badge and include evidence.

**Comment by stenington** [comment]
@cmcavoy What's supposed to happen with that evidence? Right now, open badger knows nothing about evidence, so this is a huge change potentially.

**Comment by toolness** [comment]
As I mention in my [comment](https://github.com/mozilla/openbadger/issues/128#issuecomment-18830634) in #128, if we run with the notion of "predestined claim codes" and modify the `ClaimCodeSchema` in openbadger to include, say, an `evidenceUrls` array, then openbadger could simply "hold onto" the evidence until CSOL-site retrieved it whenever the badge's claimant came by to accept it. Because actual ownership of the evidence would change at this time, we'd probably want CSOL-site to actually copy the content of the evidence URLs to its own storage and generate new permanent URLs for them, rather than simply retaining the temporary evidence URLs that openbadger gave it. Thus, once the claim code was finally claimed, the data at the temporary evidence URLs would also be deleted.

**Comment by cmcavoy** [comment]
For MVP, let's allow the issuer to add a url (or url's) that we store. Have the API return an evidence array so we can use the videos / pictures in CSOL-site. For now, on CSOL we'll just provide links to the evidence, but in the future we can use @humph 's hubble project to actually pull the asset and display it.

**Comment by cmcavoy** [comment]
Adding this to 2.1. 

> For MVP, let's allow the issuer to add a url (or url's) that we store.

**Comment by toolness** [comment]
Hmm, I was told that the primary use case for this is mobile--e.g. at an event, a mentor can take a photo of a kid's work and immediately give them a badge for it, using the photo as evidence--in which case inputting a URL would be completely useless. I don't think it'd be that much more effort to just add the ability to upload files... and since all major mobile browsers support uploading of photos and videos from file input boxes in web pages, it should work decently.

I am going to start working on this unless there are any major objections.

**Comment by iamjessklein** [comment]
@toolness that was my understanding as well re: requirements optimizing for mobile.

**Comment by threeqube** [comment]
Mobile is a primary use case for uploading evidence. However if this is going to be a huge level of effort we can prioritize desktop if that's an easier implementation.
