### ISSUE TITLE
Email learners they have a badge to claim

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#128]
related to #78 

email should include link to claim the badge on csol, and information about the badge.

**Comment by threeqube** [comment]
I believe what @iamjessklein discussed is as follows:
- Learners > 13
  - No email is sent to learner. Rather newly earned badges are highlighted as follows in the learner's dashboard. 

![dashboard](https://f.cloud.github.com/assets/1945209/432271/af5b3236-ae9f-11e2-91c1-e20af528d427.png)
- Learners < 13
  - Email is sent to parent. Parent claims the badge for the learner. Learner knows when the badge is earned through same dashboard notification is above for > 13 learners. 

So we don't ever really email the learners that they have a badge to claim at least I don't think...

**Comment by cmcavoy** [comment]
@threeqube we're going to send emails to over 13...

The flow is,
1. issuer puts email address into form on openbadger
2. user gets email with link to csol site with claim code embedded, example `http://chicagosummeroflearning.com/claim/1111-1111-1111-1111
3. user clicks on link
4. user is asked to log in or create an account
5. user is issued the badge

**Comment by threeqube** [comment]
Sounds good. We would need copy for that email then. @emgollie

**Comment by ghost** [comment]
I talked with @stenington a bit about this, and there were a couple questions/notable thingies that came up.

First, we don't actually have a way to distinguish between learners and guardians on the openbadger side of things.  This means that when an issuer enters an email address into openbadger and clicks the button to send them a claim code, there would currently be no way to determine whether to send a "guardian" email or a "learner" email.  

Solutions to this might be:

1) send a generic email that works for both guardians and learners, or 

2) to include a checkbox in the openbadger issuer interface that allows the issuer to specify that they are sending the email to a guardian, not directly to the learner.

The second issue is that, because these claim codes sent out via email can be claimed without going through the approval process that is used for claim codes given out physically/verbally, it might be possible for a clever under-13 learner to manually construct a url of this form using a physical claim code they'd been given.  This would allow them to bypass the guardian approval process that they would have to go through if they used the normal badge-claim interface.  I'm not sure whether this is problematic or not.

**Comment by ghost** [comment]
OK, a little more discussion, and...

The "second issue" above can be avoided by making it so that the urls in the emails only work for either >13 learners or guardians.  If clicked by a >13 learner, it will issue the badge to them.  If clicked by a <13 learner, it will tell them to have their guardian log in in order to be granted the badge.  Finally, if clicked by a guardian, the guardian will be presented with a list of their learners and told to select the appropriate learner to grant the badge.

That last bit may somewhat problematic since there would currently be no way for the guardian to be told in the email which learner the badge is for.  We could prompt for a child name in the issuing interface, though I'm not sure if we're allowed to use names of <13 children due to COPPA.  If it makes a difference, the name would not be stored anywhere and would only be used to construct the email being sent, and then be discarded.

**Comment by toolness** [comment]
> It might be possible for a clever under-13 learner to manually construct a url of this form using a physical claim code they'd been given.

One way to get around this is for Openbadger to HMAC sign the claim code with, say, the `OPENBADGER_JWT_SECRET` that both it and CSOL-site know. Or alternatively, since both sites already use JWTs to communicate with each other, the claim code could just be included in a JWT.

**Comment by toolness** [comment]
@christensenep, @stenington: I'm thinking it might actually be useful for us to simply extend the [ClaimCodeSchema](https://github.com/mozilla/openbadger/blob/32e700984f3221c6e952e4e96f67c47c8aafe731/models/badge.js#L25) in openbadger to include a `toBeClaimedBy` field, which is the email address of the user that the claim is predestined for.

We could then add, say, a `PREDESTINED_CLAIM_CODE_WEBHOOK_URL` environment variable to openbadger, which for all intents and purposes will just be a callback webhook to CSOL-site that gets pinged whenever one of these special claim codes is created. It's then up to CSOL-site to query openbadger further (we can add new API endpoints/filters for predestined claim codes) and email the user itself.

I _think_ this will resolve all the funky issues with openbadger not knowing about CSOL-site users, as well as a number of other problems we face with issuing badges from the openbadger side, such as #122.

**Comment by stenington** [comment]
The `toBeClaimedBy` can't actually be the claimer's email address, because of the <13 scenario in which a parent's email address gets inputted to Open Badger, but the badge should ultimately go to their child's account. But, if the parent is logged in to CSOL, we could send their email address across in the JWT auth token, and the child's fake email in the actual "please claim this badge with this address" part, and then the `toBeClaimedBy` can compare to the JWT `prn`. 

In the >13 case, both the JWT `prn` and "please claim this badge with this address" address would be the same, so it works fine there too.

**Comment by cmcavoy** [comment]
> @christensenep, @stenington: I'm thinking it might actually be useful for us to simply extend the ClaimCodeSchema in openbadger to include a toBeClaimedBy field, which is the email address of the user that the claim is predestined for.

agreed with @stenington, plus we don't want to have to explain to the earner that they have to give us the email address that the badge is going to be tied to. We've seen that be an issue in the backpack, so get to bypass it by emailing them a claim code.

**Comment by threeqube** [comment]
@cmcavoy what does the email to the earner have to say?

**Comment by emgollie** [comment]
Draft email copy per a chat with @christensenep. If this is correct I will draft the corresponding copy re: inputting email address et al. 

PARENT/GUARDIAN EMAIL
Subject: [Earner name] can claim their Chicago Summer of Learning badge!

E-mail copy:
Congrats! The [Badge name] badge is ready for [Earner name] through the Chicago Summer of Learning. 

Click here [Link to claim badge or create an account first] to claim this badge. If you have multiple accounts for badges, you'll want to make sure to log in as [Earner name].

The Chicago Summer of Learning is a citywide effort to engage young people in hands-on learning. More than 100 organizations have come together to integrate learning into summer activities for youth in every Chicago neighborhood. Join us! [Link to CSOL landing page]

From your friends at Chicago Summer of Learning

> 13 YOUTH EMAIL
> Subject: You can claim your Chicago Summer of Learning badge!

E-mail copy:
Congrats! The [Badge name] Badge is ready for you through the Chicago Summer of Learning. 

Click here [Link to claim badge or create an account first] to claim this badge. You'll want to make sure to log in as [Earner name].

Well done. Keep on earning and exploring!
From your friends at Chicago Summer of Learning

**Comment by ghost** [comment]
A couple wrinkles, though someone who is more familiar with things may want to correct one or both of these:

1) In the case where a learner hasn't yet signed up on CSOL-site, we have no way of knowing whether or not they are <13 or whether the email address provided is a guardian email or learner email.  I'm not actually sure how we're supposed to handle this case.  Should there be a different email sent out if CSOL-site doesn't find a learner/guardian with the email address provided?

2) Unfortunately, in the <13 case, we don't have the earner's name.  We only ask for the email address, and if it's a guardian's email address, we don't have any way of knowing who the earner is if there are multiple earners per guardian (and even in the case where a guardian has only one learner, we don't know whether this badge is for that learner, or a new one who hasn't yet signed up).  Yeah, this unfortunately would mean the guardian has to figure out which of their kids earned the badge.  Hopefully this isn't so common that it becomes a major pain.

**Comment by toolness** [comment]
Ok, I'm working on a pull request for this in #185. Instead of `toBeClaimedBy`, though, I'm calling the property `reservedFor`.

**Comment by toolness** [comment]
Hmm, so I was thinking that the only times the webhook would be called would be when someone on openbadger "issues" a badge, and when a user auto-earns a STEAM badge. However, I don't think the latter case is a valid one, because once we use the webhook for the former case, **all badges are ultimately issued via a CSOL-site API call to Openbadger**. That means that CSOL-site will know about STEAM badge auto-awardings and can notify the recipient itself.

Let me know if I'm mistaken about this.

**Comment by toolness** [comment]
Uh ... wait. @brianloveswords, do API endpoints like POST `/v2/user/badge/<shortname>` actually tell the client what auto-awarded badges were issued, if any? If not, can they?

**Comment by brianloveswords** [comment]
@toolness it does not, but I believe it can – `Badge#award` actually calls back with three params, `(err, badgeInstance, autoAwardInstances)`, the latter being an array of badges that got awarded based on category points. We could change the API to report those.

**Comment by toolness** [comment]
Thanks loveswords.

A few comments ago I said:

> Hmm, so I was thinking that the only times the webhook would be called would be when someone on openbadger "issues" a badge ...

So, the fact that DYN (and possibly other third-party orgs) will be using openbadger's API to issue their own badges (see #177 and mozilla/CSOL-site#104) upends this.

(╯°□°）╯︵ ┻━┻

If CSOL-site is the one sending out the emails, it will either _always_ need to be notified of every single badge issuance via webhook, or third-party sites issuing badges will need to use a different API endpoint that actually generates a reserved claim code (which would effectively be the same thing as "issuing" badges through the openbadger admin interface).

Or something like that. At this point our bizarre CSOL-site/openbadger architecture, combined with COPPA laws, combined with the fact that multiple organizations are going to be issuing badges through a variety of mechanisms, makes email issuance pretty complicated. It might be useful to create a flowchart.

┬─┬﻿ ノ( ゜-゜ノ)

**Comment by ghost** [comment]
Resolved in https://github.com/mozilla/openbadger/pull/195
