### ISSUE TITLE
Invalid assertion url returned by api

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadger#147]
Not sure if this is already being tracked, but the new `POST /v2/claim`, which piggybacks on the method behind `POST /v2/user/badge/:shortname`, returns an invalid assertion url on success. The url returned is of the format `/badge/assertion/:_id`, but the badge instance lookup method is searching by `hash`, which doesn't seem to exist on badge instances any more. So... you know... that's fun.

**Comment by cmcavoy** [comment]
this seems like a healthy, solid BFD.

On Tue, May 28, 2013 at 8:28 PM, Mike Larsson notifications@github.comwrote:

> Not sure if this is already being tracked, but the new POST /v2/claim,
> which piggybacks on the method behind POST /v2/user/badge/:shortname,
> returns an invalid assertion url on success. The url returned is of the
> format /badge/assertion/:_id, but the badge instance lookup method is
> searching by hash, which doesn't seem to exist on badge instances any
> more. So... you know... that's fun.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/147
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by toolness** [comment]
Sometimes I really miss static typing.

**Comment by toolness** [comment]
Hmm, are you sure that the `hash` property doesn't exist on badge instances anymore? I think that property was removed from badge _types_, but not badge _instances_... In fact I just wrote a test that proves it, I think, in 8ad090c9684428163135fe8deaa9f27e5a3a8fb0.

I think the problem is rather that `POST /v2/claim` just needs to be returning a URL of the format `/badge/assertion/:hash` rather than `/badge/assertion/:id`.

I think I might know of a way to test this that ensures the `POST /v2/claim` and `/badge/assertion/:hash` endpoints integrate properly going forward.

**Comment by toolness** [comment]
Um, wow. There is a method `BadgeInstance.prototype.makeAssertion()` that is never being called when the badge instance is created, and as a result the hash is never being set, so even when I fix `BadgeInstance.prototype.relativeUrl()` to return the hash instead of the id, it's still completely wrong.

The good news is that I'm writing a regression test to explore this phenomenon, so once I figure out how to fix this, the problem won't bug us again... And it will also be easier to write integration tests that exercise our actual routes and much of our middleware.

**Comment by toolness** [comment]
This bug is hilarious.

**Comment by brianloveswords** [comment]
Ugh, yeah. We should be looking up things by id now -- that hash thing was from The Old Version, which used the native mongo ids rather than the string ids we are using now.

**Comment by toolness** [comment]
Oh. Well, uh, I guess I am getting things to work The Old Way, and writing a test for it while I do it, so once I'm done with that I will fix things to work the New Way, and verify that things still work because I won't have to change the test.

**Comment by brianloveswords** [comment]
Oh yeah, definitely feel free to fix it however you feel is best.

**Comment by toolness** [comment]
Oh, apparently I can't make it work the old way, because using the assertion hash in the assertion URL can't be done since the assertion URL has to appear in the assertion itself.

Sooo, implementing it the new way now!
