### ISSUE TITLE
Duplicate claiming

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadger#153]
Claiming an unused claim code for a badge you already have reports an error, but ends up claiming the badge a second time anyway.

If I set up a badge with claim codes A and B, I can use the API to claim A with no problem. If I then try to claim B, the API reports an error but I can see in the openbadger admin console that my email is now associated with both claim codes.

**Comment by brianloveswords** [comment]
Ah, so I think the problem is it doesn't actually check if the user already owns a badge before it does the claim. So the claim goes through, then an error happens when it tries to give the user another instance (which is disallowed). We should throw a `BadgeInstance.userHasBadge` into the mix somewhere.

**Comment by toolness** [comment]
Bloody hell, it's my fault! I even wrote a [TODO](https://github.com/mozilla/openbadger/commit/b33e06834ea6df557594be793b052823da895786#L1R154) about it in the code, but didn't realize the particular edge case you discovered. Guess I am on the hook.
