### ISSUE TITLE
/v2/user/badge/<shortname> endpoint

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadger#159]
Do it plox: https://github.com/mozilla/openbadger/wiki/APIv2#get-v2userbadgeshortname

Note that there's some flexibility in the endpoint description now. You should probably update the wiki once the endpoint is actually implemented to reflect reality, or let me know so I can update it.

**Comment by toolness** [comment]
I updated the API docs too, here is the changeset: https://github.com/mozilla/openbadger/wiki/APIv2/_compare/38dc75df520ad1bf8f1b38f89a71b6cd92d429f7...f729852a032e0bfdf2a6effb5de2919283e65bf3

**Comment by toolness** [comment]
Note that I ended up making the response look a little bit like the old OpenBadges badge spec... `badge` contains the instance information, but `badge.badgeClass` contains the badge class information. I kind of wanted to call `badgeClass` just `class`, but because that's a reserved word in JavaScript, I wasn't sure if it'd fly. If we really want to, though, we can change it. Let me know what you think!
