### ISSUE TITLE
Send an email when user earns a STEAM badge

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#166]
Process for this email,
1. send user information to iRemix
2. iRemix returns a token
3. assemble email, including link to iRemix with embedded token
4. send email to user

**Comment by threeqube** [comment]
We probably need someone to write up that email. What does it need to say? cc/ @emgollie

**Comment by emgollie** [comment]
Can do. @cmcavoy, mind telling us more?

**Comment by cmcavoy** [comment]
mock copy

Dear Friend,

Because of your hard work at Science badges, you get a S badge, you're
super good at Science. Now you get to do more things at iRemix, because
it's a city level challenge thing. Here's the link to iRemix LINK. You are
great at science.

Your Friend,
Badges

On Sat, Jun 1, 2013 at 12:35 PM, Emily Goligoski
notifications@github.comwrote:

> Can do. @cmcavoy https://github.com/cmcavoy, mind telling us more?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/166#issuecomment-18793371
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by emgollie** [comment]
Do we have a STEAM field option (i.e. Science)?

Copy:

Dear [earnername],

Congrats! You've earned the [Badge Name] Badge for great work in [STEAM field].

You were awarded this badge because you earned it. It's the result of your hard work. 

Now you can try more fun city-level challenges at iRemix here: [iRemix LINK]

Keep on earning and exploring!
From your friends at the Chicago Summer of Learning

**Comment by cmcavoy** [comment]
I think we do, but if not, we'll tweak.

On Sat, Jun 1, 2013 at 12:51 PM, Emily Goligoski
notifications@github.comwrote:

> Do we have a STEAM field option (i.e. Science)?
> 
> Copy:
> 
> Dear [earnername],
> 
> Congrats! You've earned the [Badge Name] Badge for great work in [STEAM
> field].
> 
> You were awarded this badge because you earned it. It's the result of your
> hard work.
> 
> Now you can try more fun city-level challenges at iRemix here: [iRemix
> LINK]
> 
> Keep on earning and exploring!
> From your friends at the Chicago Summer of Learning
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/166#issuecomment-18793723
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by threeqube** [comment]
What do you mean by STEAM field?

**Comment by emgollie** [comment]
To identify which area you earned recognition within: ...for great work in math (or arts, or engineering, etc.)

**Comment by threeqube** [comment]
Ah gotcha. Makes sense. :koala:

**Comment by threeqube** [comment]
What's the final copy for this? @emgollie

**Comment by emgollie** [comment]
Final copy:

Hi [earnername],

Congrats! You've earned the [Badge name] Badge for great work in [STEAM field].

You were awarded this badge because you earned it. It's the result of your hard work.

Now you can try more fun city-level challenges at iRemix here: [iRemix LINK]

Keep on earning and exploring!
From your friends at the Chicago Summer of Learning

Linked fields:
[earnername]
[Badge name]
[STEAM field]
[iRemix LINK]

**Comment by iamjessklein** [comment]
:+1:
