### ISSUE TITLE
POST to /v2/user/badge/[badge name] does not return a response

### ISSUE THREAD

**Issue by mark-ellul** [mozilla/openbadger#177]
When trying to award a badge manually the server does not send a response.

I am pretty sure the badge has been awarded,  because when I try the same request again I get a user `[email]` already has badge.

**Comment by cmcavoy** [comment]
for context, @mark-ellul is working with iRemix / DYN. They're going to be issuing badges via openbadger as part of CSOL. /cc @brianloveswords @toolness

**Comment by cmcavoy** [comment]
This one is also blocking @andrewhayward it now seems like when you make this call it crashes openbadger.

**Comment by toolness** [comment]
As a side note, realizing that there are more consumers of this API endpoint than just CSOL-site makes me realize that our plans to [email learners they have a badge to claim](https://github.com/mozilla/openbadger/issues/128) might have just gotten a bit more complicated.

Will DYN be emailing/notifying the badge recipients itself, or does it expect openbadger to do that?  And will it ever be issuing badges to folks < 13, in which case the email it's providing to this endpoint may actually be the email of the kid's guardian rather than the actual badge recipient? And does DYN expect any evidence to show up on the user's account on CSOL-site?

**Comment by mark-ellul** [comment]
@toolness hi, we do email our users when they have been awarded a badge. if the user is <13 and mozilla has provided the parent's email address we email the parents as well.

The only emails that we expect open badger / csol to send is described in this issue 
https://github.com/mozilla/CSOL-site/issues/104

With respect to evidence showing up on the Mozilla CSOL-site, I am assuming no, but I will leave it to our CEO  to decide on this, I will pass this issue for him to decide.

**Comment by cmcavoy** [comment]
@mark-ellul @toolness in discussions with DYN (not sure what Akili's github name is) we agreed that all badges issued by iRemix for CSOL will go through OpenBadger, so any communication OpenBadger does for entry level CSOL badges, it should do for iRemix CSOL badges.

If we end up double communicating, that's preferable to complicating this issue. AFAIK, users won't be leveling up to iRemix for a few weeks, or at least until after June 17. So we have some breathing room to tweak the communication if necessary.

**Comment by threeqube** [comment]
Akili is @rl

**Comment by rl** [comment]
Agree w @cmcavoy that for the time being I wouldn't worry too much about potential double notifications, bigger things to tackle at the moment.

In terms of whether or not we will be including evidence with issued badges, its a bit of a complicated question for us. Normally we'd of course want to do this across the board as we of course believe the evidence associated with the badge is really what adds much of the value to them. 

The thing we have to consider though, to @cmcavoy's point earlier, every badge issued by iRemix will automatically be pushed to OpenBadger. However, kids are uploading their media to earn the badges within a private community where its understood that only folk in that community have access to things posted. 

In our model, anytime a post is made available outside of iRemix, that only happens when the user who posted it specifically changes the sharing settings themselves. In the case of CSOL where badges are pushed outside of iRemix automatically w/o user intervention (beyond having submitted for it), the user doesn't have the ability to control whether they want their post being accessible outside of the private network or not (we'd have to produce a publicly accessible URL to pass as evidence).

We've got to grapple w/ that a bit and see if there's a healthy/responsible middle ground for summer.

In our normal workflow, badges are issues only internal to iRemix and the user then chooses to push it to their backpack or not. In that case, we could work in evidence as the user controls what's pushed out or not. For CSOL, its automated so there's a new set of implications on our end to consider. 

@toolness @cmcavoy what are the implications on you all's end if we do or don't include evidence?

**Comment by cmcavoy** [comment]
@rl we'd rather not take the evidence...so we all agree! Keep the evidence
private in iRemix....

On Wed, Jun 5, 2013 at 4:28 PM, rl notifications@github.com wrote:

> Agree w @cmcavoy https://github.com/cmcavoy that for the time being I
> wouldn't worry too much about potential double notifications, bigger things
> to tackle at the moment.
> 
> In terms of whether or not we will be including evidence with issued
> badges, its a bit of a complicated question for us. Normally we'd of course
> want to do this across the board as we of course believe the evidence
> associated with the badge is really what adds much of the value to them.
> 
> The thing we have to consider though, to @cmcavoyhttps://github.com/cmcavoy's
> point earlier, every badge issued by iRemix will automatically be pushed to
> OpenBadger. However, kids are uploading their media to earn the badges
> within a private community where its understood that only folk in that
> community have access to things posted.
> 
> In our model, anytime a post is made available outside of iRemix, that
> only happens when the user who posted it specifically changes the sharing
> settings themselves. In the case of CSOL where badges are pushed outside of
> iRemix automatically w/o user intervention (beyond having submitted for
> it), the user doesn't have the ability to control whether they want their
> post being accessible outside of the private network or not (we'd have to
> produce a publicly accessible URL to pass as evidence).
> 
> We've got to grapple w/ that a bit and see if there's a
> healthy/responsible middle ground for summer.
> 
> In our normal workflow, badges are issues only internal to iRemix and the
> user then chooses to push it to their backpack or not. In that case, we
> could work in evidence as the user controls what's pushed out or not. For
> CSOL, its automated so there's a new set of implications on our end to
> consider.
> 
> @toolness https://github.com/toolness @cmcavoyhttps://github.com/cmcavoywhat are the implications on you all's end if we do or don't include
> evidence?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/openbadger/issues/177#issuecomment-19009918
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by brianloveswords** [comment]
So I think the problem with not getting a response was because the route was crashing the server for some reason – it would award the badge, but take down the node before responding. When you would try again, it would hit a different node, but the badge would be in the database already.

While I'm in here though, what are you expecting/what do you need from the response? Just the url to the badge assertion, or do you also need the badge class information reflected?

**Comment by mark-ellul** [comment]
@brianloveswords  Is the assertion URL the link to that badge in the backpack? If so yes that would be cool, in a normal json with status "ok".

If its possible could you allow for an optional evidence URL to be passed in and saved to the Badge if its passed in?

**Comment by brianloveswords** [comment]
@mark-ellul it's a URL pointing to the assertion hosted on OpenBadger. The badge will show up in the CSOL backpack, though.

I can modify the award route to take evidence.

**Comment by mark-ellul** [comment]
Thanks, let me know what the updated route is, i am not sure if I have the ability to update the api documentation though.

**Comment by brianloveswords** [comment]
It'll be the same route, but once #199 lands, you'll be able to pass in an `evidence` parameter as well.

**Comment by mark-ellul** [comment]
@brianloveswords  thanks, I just checked your commits in the pull request and saw that, I love Open Source! 

Is there a way for me to know when #199 lands?

**Comment by cmcavoy** [comment]
i'm merging #199 now and will launch to staging asap....probably by 11:30 CT

**Comment by mark-ellul** [comment]
@cmcavoy Awesome, thanks for the quick turnaround guys!

**Comment by brianloveswords** [comment]
No problem @mark-ellul, let us know if you run into any other issues!
