### ISSUE TITLE
Criteria returned from API has (required) at the end of it.

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#211]
We also need to use the criteria in the badge-detail page on CSOL, is there a way to get it without the Rubric markup? Check http://csol-aws.mofostaging.net/earn/foundations-of-ecology as an example of how we're using the criteria from the API.

**Comment by toolness** [comment]
there's no way that the criterias in the badges can be modified to be in the format we expected the rubrics to be in, e.g. where required items have no markup and optional ones say "(optional)"?

Easiest way to do this might be to hack the rubric-parser to remove "(required)" from any items, and add "(optional)" to ones that don't have "(required)" in them, because our current way of doing things extends through to aestimia and would be hard to change otherwise.

**Comment by cmcavoy** [comment]
@toolness in the [badge record on openbadger](http://openbadger-csol.mofostaging.net/admin/badge/foundations-of-ecology) there's still 'criteria' that hasn't been parsed into the rubric. Are both versions of the criteria (parsed and unparsed) available in the API? I think that's all I'm looking for, the original criteria for the page, the rubric for aestimia.

**Comment by toolness** [comment]
yup both are available bro.

**Comment by cmcavoy** [comment]
this is on the csol side...closing
