### ISSUE TITLE
Need to increase the capacity of the issuer tool

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#261]
If you put in more than 20 emails, the system dies.

We have requests for batches of upwards of 600 emails at a time. We need to build a queue, or some way of handling these offline.

This is a high priority request, but can wait until Monday when you guys are back.

/cc @toolness

**Comment by brianloveswords** [comment]
## Cron + simple script approach

Easiest thing to do from a programming perspective is to write a script which looks at a queue (let's just say a `work` collection in the mongo database), and processes all of them one-by-one to completion (atomic `findAndModify` with a limit of 1 pluck a task and mark as `started`, process task, `findAndModify` to mark as `complete`). We could set up a cron job to run every couple of minutes.

**Time Estimate**
Half a day + sysadmin for setting up cron

**Pros**
- Easy to test
- Easy to write
- Robust: cron is well tested, and the script runs to completion (rather than being a long-lived process)

**Cons**
- I kinda don't like cron
- We'd have to make sure to test race condition: what happens if the cron job tries to run the script again and it's not done processing yet? It _should_ be fine, but we'd have to test that.

## Worker process approach

Slightly harder, but possibly more robust, is to start a "worker", a new child process of the main app, with each app instance. Have something like `worker.addTasks` which adds the tasks to a task pool (that database collection). Whenever `addTasks` is called, it also starts processing the queue in the same manner described above. `addTasks` can also return an EventEmitter instance that can emit lifecycle events for each task ("started", "error", "done", etc.)

**Time Estimate**
A day

**Pros**
- Better reporting
- Fairly easy to test
- Proactive: doesn't rely on polling to start queue operations

**Cons**
- Requires long-running process and defensive programming to make sure the process doesn't go down.

**Comment by cmcavoy** [comment]
> We'd have to make sure to test race condition: what happens if the cron job tries to run the script again and it's not done processing yet? It should be fine, but we'd have to test that.

Mark the record as "in process".

> Slightly harder, but possibly more robust

I think if we went this route, I'd rather just see us implement an actual queue service, or start using Amazon SQS.

**Comment by brianloveswords** [comment]
> Mark the record as "in process".

Yeah, that's why I'm saying "it should be fine" since `findAndModify` is supposed to be atomic. But we'd still have to test it.

> I think if we went this route, I'd rather just see us implement an actual queue service, or start using Amazon SQS.

That's more than a day, though, to implement and test since that involves bringing in more moving parts. It depends on how fast you want this done.

**Comment by cmcavoy** [comment]
So - the difference between the two approaches is really - cron, or fork a worker.

I'm fine taking the extra time to fork the worker, but we should ping @jdotpz and make sure he's ok with monitoring the process, or if he'd rather just do cron.

**Comment by jdotpz** [comment]
Cron is going to be far faster and easier to implement in the here and true.  

We can setup whichever app on a non-web serving node, and have it run cron jobs with the appropriate env (sourced from /var/www/appname/.env) as its operating environment.

One concern here would be the potential for a node to die, and the queue to be affected.  What happens if a node says it is handling a message, but dies before reporting back?
