### ISSUE TITLE
Badges need orgs AND programs

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#75]
Not sure if this is represented, but I forgot that the hierarchy is:

Organizations have (many) programs, programs have (one or more) badges.

One to many in each case.

**Comment by brianloveswords** [comment]
From an access control perspective, are the users (as in the people who will log in to issue badges) going to be scoped to organization or program?

**Comment by brianloveswords** [comment]
ALSO, will every organization have programs? Will badges always be scoped to programs, or will they sometimes be scoped to organizations?

**Comment by cmcavoy** [comment]
1. i'd like to scope them to organizations, but a few of the orgs are very large, so I anticipate this might be difficult. Go with orgs for now, but understand we might need to adjust when the data comes in.
2. every organization will have programs, or at least one program.

**Comment by threeqube** [comment]
@carlacasilli can best answer this but @cmcavoy seems right. 

Badges will always be scoped to programs. 
Every organization will have a program or programs.

**Comment by carlacasilli** [comment]
For the most part, badges are issued by programs and organizations run programs. Sunny's equation is almost always right (Badges < Programs < Orgs). However, ASM is slightly different in that they're an org and the badges are named after them rather than the programs that they represent. It's not clear who is actually issuing them, ASM or the individual programs that ASM is funding.

Also, the self-paced activities are run through different programs (and orgs) but will be issued from DYN and they're an org, not a program.

Yay!

**Comment by cmcavoy** [comment]
Hey @carlacasilli we have to figure out how to make ASM fit into the model of orgs > programs > badges. We can't change the data model. We can reevaluate for post launch, but for June 1, everyone needs to fit into orgs > programs > badges.
